spring.application.name=demo

server.port=${PORT:8080}

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/blog}
spring.data.mongodb.database=${MONGODB_DATABASE:blog}
spring.data.mongodb.auto-index-creation=true

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
