spring.application.name=demo

server.port=8081

spring.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=true

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
#spring.datasource.username=root
#spring.datasource.password=
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.mong

#jwt.secret=qwertyuioasdfghjklzxcvbnm,1234567890()!@#$%^&*_+-?><}{|:"~`|
#jwt.expiration=86400000